### ISSUE TITLE
gIntersection speed improvement suggestion

### ISSUE THREAD

**Issue by kendonB** [rundel/rgeos#3]
The gIntersection command doesn't seem to first check the bounding boxes of the polygons being compared. As a result, when gIntersecting two large polygons (like counties and land use), it can take a very long time.

The below code first checks that the bbox's of the polygons do overlap before proceeding to the more detailed check.

    library(rgeos)
    load("rgeos_eg.RData")
    bbox(detailed_poly)
    # These don't overlap at all
    bbox(other_poly)
    system.time(intersection <- gIntersection(other_poly, detailed_poly))
    # Returns NULL very slowly
    
    # a better version - but only works when each object has one polygon; 
    # would have to be implemented deep in the algorithm
    gIntersection_new <- function(spgeom1, spgeom2, byid=FALSE, id=NULL, drop_lower_td=FALSE){
      # From http://stackoverflow.com/a/25369187/2726309
      if((max(bbox(spgeom1)[1,2], bbox(spgeom2)[1,2]) - 
          min(bbox(spgeom1)[1,1], bbox(spgeom2)[1,1]) >
          bbox(spgeom1)[1,2] - bbox(spgeom1)[1,1] + 
          bbox(spgeom2)[1,2] - bbox(spgeom2)[1,1]) |
         (max(bbox(spgeom1)[2,2], bbox(spgeom2)[2,2]) - 
          min(bbox(spgeom1)[2,1], bbox(spgeom2)[2,1]) >
          bbox(spgeom1)[2,2] - bbox(spgeom1)[2,1] + 
          bbox(spgeom2)[2,2] - bbox(spgeom2)[2,1])){
        return(NULL)
      } else {
        return(gIntersection(spgeom1, spgeom2, byid=byid, id=id, drop_lower_td=drop_lower_td))
      }
    }
    system.time(intersection_new <- gIntersection_new(other_poly, detailed_poly))
    # Returns NULL very quickly

[rgeos_eg.zip](https://github.com/rundel/rgeos/files/98491/rgeos_eg.zip)

**Comment by rsbivand** [comment]
This is *not* where the development version is kept - it is kept on
R-forge.

These are effectively trivial findings, that have been known since
forever. The code in ASDAR ch. 5 2nd edition:

http://www.asdar-book.org/book2ed/cm2_mod.R

around chunk 39 ff.
 
Use gBinarySTRtreeQuery() to build a list of objects with intersecting   
envelopes, then use gIntersection on these by-element subsets.
Alternatively, use the (newer) returnDense=FALSE to return a (similar)
list from gIntersects instead of a logical matrix.

If these suggestions don't resolve the issue, please let me know.

Roger

PS. this is a copy of my email reply top the issue poster

**Comment by kendonB** [comment]
As Roger suggests, one can use ``gBinarySTRtreeQuery`` to achieve this:

    library(rgeos)
    library(sp)
    load("/Users/Kenny/Desktop/rgeos_eg.RData")
    # Generates a list of ones and zeroes indicating 
    tmp <- gBinarySTRtreeQuery(other_poly, detailed_poly)
    overlapping_lgl <- !sapply(tmp, is.null)
    if (any(overlapping_lgl)){
      new_poly <- gIntersection(other_poly, detailed_poly[overlapping_lgl,])
    } else {
      new_poly <- NULL
    }
